const data={
    productItems:[
    {
        id:"1",
        names:"Clearly Natural - Lemon Soap with Essential Oils and Natural Glycerine, 113g",
        rating:"4.7",
        review:"8549 reviews",
        price:249.00, 
        price2:475.00,
        discount:"47%",
        image:"images/soap3.png",

    },
    {
        id:"2",
        names:"Lalas Herbal - With 24 Herbs, Essential Oils and Multi Vitamins, 100g",
        rating:"4.9",
        review:"7569 reviews",
        price:230.00,
        price2:460.00,
        discount:"50%",
        image:"images/soap2.png",

    },
    {
        id:"3",
        names:"Hamam - With 100% Pure Neem Oil, Tulsi and Aloe Vera, 100g",  
        rating:"4.8",
        review:"8561 reviews",
        price:240.00,
        price2:495.00,
        discount:"52%",
        image:"images/soap5.png",

    },
    {
        id:"4",
        names:"Tea Tree Therapy - Vegetable Shop with Tea Tree Oil for Everyday Use, 110g",
        rating:"4.8",
        review:"7569 reviews",
        price:349.00,
        price2:575.00,
        discount:"39%",
        image:"images/teasoap.png",

    },
    {
        id:"5",
        names:"Aloe Vera - Herbal Shop with 99% Pure Aloe Vera Extract, 100g",
        rating:"4.6",
        review:"5568 reviews",
        price:279.00,
        price2:485.00,
        discount:"42%",
        image:"images/soappng.png",

    },
    {
        id:"6",
        names:"Mirah Belle - Multani Mitti, Skin Brightening and Cleansing Soap, 80g",
        rating:"4.9",
        review:"6564 reviews",
        price:449.00,
        price2:620.00,
        discount:"28%",
        image:"images/soap4.png",

    }
], productItems2:[
    {
        id:"7",
        names:"Mesmara - Cold Pressed , Virgin Castor Oil for Healthy Skin and Hair, 200ml",
        rating:"4.8",
        review:"6895 reviews",
        price:350.00, 
        price2:620.00,
        discount:"44%",
        image:"images/castoroil.png",
    },
    {
        id:"8",
        names:"Deve Herbs - Finest Quality Pure Bhringraj Herbal Oil for all Hair Type, 150ml",
        rating:"4.9",
        review:"7204 reviews",
        price:389.00,
        price2:595.00,
        discount:"35%",
        image:"images/Bhringrajoil.png",
    },
    {
        id:"9",
        names:"Herbs Forever - Amla Oil , Herbal Massage Oil made with Organic Herbs, 210ml",
        rating:"4.6",
        review:"8835 reviews",
        price:240.00,
        price2:495.00,
        discount:"51%",
        image:"images/amlaoil.png",
    },
    {
        id:"10",
        names:"Mountain Rose Herbs -Certified Organic Rosemary Herbal Oil, 60ml",
        rating:"4.9",
        review:"9552 reviews",
        price:649.00,
        price2:928.00,
        discount:"32%",
        image:"images/rosemaryoil.png",
    },
    {
        id:"11",
        names:"Africa's Best - Ultimate Multi-purpose Herbal Oil with Organic Herbs, 237ml",
        rating:"4.9",
        review:"7569 reviews",
        price:449.00,
        price2:620.00,
        discount:"28%",
        image:"images/africaoil.png",
    },
    {
        id:"12",
        names:"SSG Homemade - Herbal Hair Oil infused with 13+ Natural Herbs, 200ml",
        rating:"4.9",
        review:"8542 reviews",
        price:395.00,
        price2:529.00,
        discount:"26%",
        image:"images/herbaloil.png",
    }
    
],productItems3:[
    {
        id:"13",
        names:"Refreshing Tonic - Mint Tonic for Strongner Tooth and Gums, 150ml",
        rating:"4.8",
        review:"9295 reviews",
        price:380.00, 
        price2:679.00,
        discount:"56%",
        image:"images/mint-tonic.png",
    },
    {
        id:"14",
        names:"Desert Essence - Neem Toothpaste with no Fluoride , SNS and Gluten, 176g",
        rating:"4.9",
        review:"7204 reviews",
        price:389.00,
        price2:595.00,
        discount:"35%",
        image:"images/paste2.png",
    },
    {
        id:"15",
        names:"Mint Mouthwash - For Teeth Whitening and Remove Bad Breath, 250ml",
        rating:"4.7",
        review:"8836 reviews",
        price:290.00,
        price2:498.00,
        discount:"43%",
        image:"images/mouthwash.png",
    },
    {
        id:"16",
        names:"Panch Shakti - Black Dant Manjan with Neem and 14 other Natural Herbs, 100g",
        rating:"4.9",
        review:"9552 reviews",
        price:350.00,
        price2:567.00,
        discount:"39%",
        image:"images/dant-manjan2.png",
    },
    {
        id:"17",
        names:"IMC Dental Cream - Aloe Vera Dental Cream for Complete Dental Care, 100g",
        rating:"4.8",
        review:"7569 reviews",
        price:269.00,
        price2:420.00,
        discount:"26%",
        image:"images/paste1.png",
    },
    {
        id:"18",
        names:"Uttam Herbal - Dant Manjan with 5 other herbal ingredients for Toothache Problems, 120g",
        review:"8432 reviews",
        price:395.00,
        price2:529.00,
        discount:"26%",
        image:"images/paste5.png",
    }
],productItems4:[
    {
        id:"19",
        names:"Happy Herbals - Ashwagandha Powder for Supporting Health, 100g",
        rating:"4.8",
        review:"9295 reviews",
        price:219.00, 
        price2:367.00,
        discount:"41%",
        image:"images/ashwagandha.png",
    },
    {
        id:"20",
        names:"Herbalife Nutrition - Multivitamin Mineral and Herbal Tablets Plus, 60 pcs",
        rating:"4.9",
        review:"7204 reviews",
        price:389.00,
        price2:595.00,
        discount:"35%",
        image:"images/multi-vitamin.png",
    },
    {
        id:"21",
        names:"Bixa Botenical - Giloy Stem Powder for Immunity Support, 200g",
        rating:"4.7",
        review:"8836 reviews",
        price:479.00,
        price2:628.00,
        discount:"24%",
        image:"images/giloy-powder.png",
    },
    {
        id:"22",
        names:"Grenera - Amla Powder for Natural Dietary Supplements, 100g",
        rating:"4.9",
        review:"9552 reviews",
        price:350.00,
        price2:567.00,
        discount:"39%",
        image:"images/amla-powder.png",
    },
    {
        id:"23",
        names:"Herbal Hills - Imunohills Cream for immunity support, 30 pcs",
        rating:"4.8",
        review:"7569 reviews",
        price:269.00,
        price2:420.00,
        discount:"26%",
        image:"images/immunity-capsule.png",
    },
    {
        id:"24",
        names:"Devagya -Pure Natural Shudh Shilajit for Boosting Energy, 100g",
        review:"8432 reviews",
        price:395.00,
        price2:529.00,
        discount:"26%",
        image:"images/shilajit.png",
    }
],productItems5:[
    {
        id:"25",
        names:"Atulya - Amla & Bhringraj Shampoo for Complete Hair Treatment, 100ml",
        rating:"4.8",
        review:"9295 reviews",
        price:319.00, 
        price2:467.00,
        discount:"32%",
        image:"images/amla-bhringa-shampoo.png",
    },
    {
        id:"26",
        names:"Starflower Essentials - Moringa Herbal Shampoo for All Hair Types, 80ml",
        rating:"4.9",
        review:"7204 reviews",
        price:479.00,
        price2:628.00,
        discount:"24%",
        image:"images/moringa-shampoo.png",
    },
    {
        id:"27",
        names:"Swaranakshri - Heena & Shikakai Natural Herbal Conditioner, 500ml",
        rating:"4.7",
        review:"8836 reviews",
        price:679.00,
        price2:928.00,
        discount:"27%",
        image:"images/Heena-Sikakai_shampoo.png",
    },
    {
        id:"28",
        names:"Orange Hibiscus - Herbal Hair Conditioner for Frizz Free Hair, 200ml",
        rating:"4.9",
        review:"9552 reviews",
        price:350.00,
        price2:567.00,
        discount:"39%",
        image:"images/hibiscus-conditioner.png",
    },
    {
        id:"29",
        names:"Himalayan Organics - Tea Tree Shampoo for Hair Fall Control, 100ml",
        rating:"4.8",
        review:"7569 reviews",
        price:269.00,
        price2:420.00,
        discount:"26%",
        image:"images/tea-shampoo.png",
    },
    {
        id:"30",
        names:"Noubalm -Natural Dry Shampoo Powder with Zesty Oils, 100g",
        review:"8432 reviews",
        price:395.00,
        price2:529.00,
        discount:"26%",
        image:"images/dry-shampoo.png",
    }
],productItems6:[
    {
        id:"31",
        names:"Orgaglo Naturals - Vitamin C Skin Brightening Night Cream, 50g",
        rating:"4.8",
        review:"9295 reviews",
        price:419.00, 
        price2:767.00,
        discount:"46%",
        image:"images/vitaminc-cream.png",
    },
    {
        id:"32",
        names:"Ayur Herbals - Cold Cream with Aloe Vera and Vitamin E, 80g",
        rating:"4.9",
        review:"7204 reviews",
        price:279.00,
        price2:528.00,
        discount:"47%",
        image:"images/cold-cream.png",
    },
    {
        id:"33",
        names:"Krishna's Herbal & Ayurveda - Pure Multani Mitti Powder, 200g",
        rating:"4.7",
        review:"8836 reviews",
        price:378.00,
        price2:630.00,
        discount:"41%",
        image:"images/multani-mitti.png",
    },
    {
        id:"34",
        names:"Orange Hibiscus - Herbal Hair Conditioner for Frizz Free Hair, 200ml",
        rating:"4.9",
        review:"9552 reviews",
        price:350.00,
        price2:567.00,
        discount:"39%",
        image:"images/hibiscus-conditioner.png",
    },
    {
        id:"35",
        names:"Vaadi Herbals - Pure Rose Water for Natural Skin Toner, 250ml",
        rating:"4.8",
        review:"7569 reviews",
        price:269.00,
        price2:498.00,
        discount:"44%",
        image:"images/rose-water.png",
    },
    {
        id:"36",
        names:"Vaadi Herbals - Anit Acne Neem Face Pack with Clove & Turmeric, 100g",
        review:"8432 reviews",
        price:339.00,
        price2:529.00,
        discount:"26%",
        image:"images/neempack.png",
    }
]


};


export default data;
